BASE_URL = "https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp"
# BASE_URL = "https://www.whatismyip.com/"
LESS_SECURE_URL = "https://myaccount.google.com/lesssecureapps"
FIRST_NAME  = "Jonathan"
LAST_NAME = "Perez"
PHONE = "13059007270"
USER_ID = "jasonpostingtest"
PASSWORD = "Tyler.1969!!!"
